{{- $ctx := . }}
{{- range .Values.apps }}
{{- $apps := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "apps require a unique name to create" .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{  include "agent.name" $apps }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      {{- range $apps.apis }}
        - name: {{ .name }}
          image: "{{ $apps.image.repository }}:{{ $apps.image.tag | default "latest" }}"
          {{- if .command }}
          command: {{ $apps.command }}
          {{- end }}
          args:
            - "{{ .name }}:{{ .app }}"
            - "--host"
            - "{{ .host }}"
            - "--port"
            - "{{ .port }}"
          ports:
            - containerPort: {{ .port }}
          env:
            {{- toYaml $apps.env | nindent 12 }}
          volumeMounts:
          - name: {{ $apps.storage.name | default "agent-volume" }}
            mountPath: {{ $apps.storage.path | default "/apps"}}
        {{- end -}}
      {{- if .storage }}
      {{- if eq .storage.type "local" }}
      volumes:
      - name: {{ .storage.name | default "agent-volume" }}
        hostPath:
          path: {{ .storage.local_path | default "/home/ubuntu/agent-workspace" }}
          type: DirectoryOrCreate
          {{- else if eq .storage.type "pvc" -}}
      volumes:
      - name: {{ .storage.name | default "agent-volume"}}
        persistentVolumeClaim:
          claimName: {{ .storage.name | default "agent" }}-pvc
          {{- end -}}
        {{- end -}}

        

{{- printf "\n---\n" }}
{{- end -}}