FROM python:3.12-slim

WORKDIR /app

# 安裝必要套件
COPY services/vm_api_jupyter/vm_api_jupyter.py /app/
COPY services/vm_api_jupyter/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# 複製所有程式碼
COPY . /app

# 預設啟動指令
CMD ["uvicorn", "vm_api_jupyter:app", "--host", "0.0.0.0", "--port", "8002"]
