apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
data:
  settings.yaml: |
    # trusted_cloud api url
    trusted_cloud_url: 'http://kong.127.0.0.1.nip.io/'

    # image server API
    server:
      # host_ip: ${VM_HOST}
      host_ip: 127.0.0.1
      port: 30002  # TODO 如果沒有值 使用https://(HOST_IP)/images
    #  image_base_url: "http://140.110.160.164:8005/images"

    # Qdrant setting
    qdrant:
      host_ip: qdrant.default.svc.cluster.local   # 或 VM IP, FIP
      port: 6333

    # Ollama setting
    ollama:
      host_ip: ollama    # 或 VM IP, FIP
      port: 11454


    # llm  url、model_name
    # "http://140.110.160.97:30002/v1"
    # "ollama"
    # "llama4-scout"
    # Creation LLM 
    openai_base_url: "http://127.0.0.1:30002/v1"
    api_key : "ollama" # enter random value if no api_key
    llm_model_name : "gpt-oss:20b" # llm model name must support MCP
    # Q&A LLM 
    openai_base_url_llm: "http://127.0.0.1:30002/v1"
    api_key_llm : "ollama"
    llm_model_name_llm : "RedHatAI/Llama-4-Scout-17B-16E-Instruct-FP8-dynamic"

    # default prompt style is basic, support: basic , structured, article_qa, k8s_instruction 
    prompt_style: "k8s_instruction"

    # reranker model output
    reranker_top: 2

    # Qdrant vector database name
    SensiMesh_Qdrant_vector_collection_name: "SensiMesh_20250519_512_10_bge-m3"
    trusted_cloud_Qdrant_vector_collection_name: "trusted-cloudEN_20250923_512_10_bge-m3"
    qdrant_ip: "qdrant.default.svc.cluster.local" 
    #ollama_ip: "10.106.185.217"
    ollama_ip: "ollama"
    # embed_model name
    embed_model_name: "qllama/bge-large-en-v1.5:latest"

    # higher the temperature makes the answer more human like but might increase change to get wrong answer
    temperature: 0.1
