apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      initContainers:
        - name: init-qdrant-data
          image: alpine/git:v2.49.1
          command:
            - sh
            - -c
            - |
              echo "Pulling Qdrant collection data..."
              # Example: clone a repo
              git clone -b dev https://github.com/kanic1111/Trusted-cloud-AIagent
              cp -r Trusted-cloud-AIagent/trusted-cloud-agent/trustedcloud_vm_manager/qdtanrDB/trusted-cloud_20250701_512_10_bge-m3/ /data
              # Or: download a tarball
              # wget -O /tmp/collection.tar.gz https://example.com/collection.tar.gz
              # tar -xzf /tmp/collection.tar.gz -C /data
          volumeMounts:
            - name: qdrant
              mountPath: /data
      containers:
        - name: qdrant
          image: "qdrant/qdrant:latest"
          ports:
            - containerPort: 6333
          env:
            - name: API_URL
              value: 0.0.0.0:6333
          volumeMounts:
          - name: qdrant
            mountPath: /qdrant/storage/collections
      volumes:
      - name: qdrant
        persistentVolumeClaim:
            claimName: qdrant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant
spec:
  type: ClusterIP
  selector:
    app: qdrant
  ports:
    - name: http
      protocol: TCP
      port: 6333         # Target port (your app's internal port)
      targetPort: 6333   # Pod containerPort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi